### ISSUE TITLE
CLI les commandes collectors run ne sont plus fonctionelles

### ISSUE THREAD

**Issue by naparuba** [naparuba/opsbro#106]
opsbro  collectors run system
┌──────────────────────────────────────── Fatal Error ────────────────────────────────────────┐
  → The call did crash: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/opsbro-0.5-py2.7.egg/opsbro/cli.py", line 668, in one_loop
    f(*cmd_args, **cmd_opts.__dict__)
  File "/var/lib/opsbro/core-configuration/packs/core-cli-collectors/cli/cli.py", line 118, in do_collectors_run
    inst.main()
  File "/usr/local/lib/python2.7/dist-packages/opsbro-0.5-py2.7.egg/opsbro/collector.py", line 190, in main
    collectormgr.put_result(self.__class__.__name__.lower(), r, list(s), self.log)
  File "/usr/local/lib/python2.7/dist-packages/opsbro-0.5-py2.7.egg/opsbro/collectormanager.py", line 204, in put_result
    key = '%s.%s.%s' % (gossiper.name, cname, mname)
AttributeError: 'Gossip' object has no attribute 'name'
.
Please fill a bug report about it.
└─────────────────────────────────────────────────────────────────────────────────────────────┘

**Comment by naparuba** [comment]
Fixed by 30e9498b2995232aa0fdc46c1a18ee4b14369bae
