### ISSUE TITLE
DAEMON: si on mets un caractères UTF8 comme nom de process, ça plante

### ISSUE THREAD

**Issue by naparuba** [naparuba/opsbro#118]
┌──────────────────────────────────────── Fatal Error ────────────────────────────────────────┐
  → The call did crash: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/opsbro-0.5-py2.7.egg/opsbro/cli.py", line 681, in one_loop
    f(*cmd_args, **cmd_opts.__dict__)
  File "/var/lib/opsbro/core-configuration/packs/core-cli-agent/cli/cli.py", line 467, in do_start
    l.do_daemon_init_and_start(is_daemon=daemon, one_shot=one_shot, force_wait_proxy=auto_detect)
  File "/usr/lib/python2.7/site-packages/opsbro-0.5-py2.7.egg/opsbro/launcher.py", line 243, in do_daemon_init_and_start
    c = Cluster(cfg_dir=self.cfg_dir)
  File "/usr/lib/python2.7/site-packages/opsbro-0.5-py2.7.egg/opsbro/cluster.py", line 299, in __init__
    libstore.get_processtitler().set_name(self.process_name)
  File "/usr/lib/python2.7/site-packages/opsbro-0.5-py2.7.egg/opsbro/processtitle.py", line 39, in set_name
    self._refresh()
  File "/usr/lib/python2.7/site-packages/opsbro-0.5-py2.7.egg/opsbro/processtitle.py", line 24, in _refresh
    self._set_process_name(process_name)
  File "/usr/lib/python2.7/site-packages/opsbro-0.5-py2.7.egg/opsbro/processtitle.py", line 30, in _set_process_name
    self.setproctitle(process_name)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 3-4: ordinal not in range(128)

**Comment by naparuba** [comment]
yep, non géré par le système.
