### ISSUE TITLE
Connection refused but Kunai is ok

### ISSUE THREAD

**Issue by martinec** [naparuba/opsbro#3]
Running Kunai in a VM (https://www.turnkeylinux.org/lampstack) and starting the service using

```
/etc/init.d/kunai start
```

It complains about a refused connection but status it's ok

```
Starting kunai
Traceback (most recent call last):
  File "/usr/bin/kunai", line 353, in <module>
    CLI.one_loop(command_args)
  File "/usr/bin/kunai", line 194, in one_loop
    f(*cmd_args, **cmd_opts.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/Kunai-0.9-py2.7.egg/kunai/cli/agent/cli.py", line 157, in do_info
    d = get_kunai_json('/agent/info')
  File "/usr/local/lib/python2.7/dist-packages/Kunai-0.9-py2.7.egg/kunai/cli/__init__.py", line 14, in get_kunai_json
    return get_json(uri, local_socket)
  File "/usr/local/lib/python2.7/dist-packages/Kunai-0.9-py2.7.egg/kunai/unixclient.py", line 99, in get_json
    (code, r) = get_local(uri, local_socket=local_socket, params=params)
  File "/usr/local/lib/python2.7/dist-packages/Kunai-0.9-py2.7.egg/kunai/unixclient.py", line 90, in get_local
    request = url_opener.open(req)
  File "/usr/lib/python2.7/urllib2.py", line 401, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 419, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 379, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/dist-packages/Kunai-0.9-py2.7.egg/kunai/unixclient.py", line 69, in unix_open
    return self.do_open(UnixHTTPConnection(unix_socket), new_req)
  File "/usr/lib/python2.7/urllib2.py", line 1181, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 111] Connection refused>
. ok 
```

**Comment by naparuba** [comment]
I'm interested with the new dev version, there are far more logs.

**Comment by naparuba** [comment]
I close the ticket as no news, and that the codedid changed a lot since this date :)
